config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/', to: 'main#index', as: :root
    resources :feedly_articles
    resources :feedly_sources
    resources :interests
    post '/interests/update', to: 'interests#update', as: :update_interests
  end

  get '/login', to: 'session#new', as: :login
  post '/login', to: 'session#create', as: :sign_in
  get '/logout', to: 'session#destroy', as: :logout

  namespace :api do
    namespace :v1 do
      post 'login', to: 'session#sign_in', as: :login
      post 'sign_up', to: 'session#sign_up', as: :sign_up

      get '/interests', to: 'interests#index', as: :interests
      post '/user/interests', to: 'user#update_interests', as: :update_interests
      get '/feed', to: 'homefeed#index', as: :homefeed
    end
  end
end

app/models/feedly_source.rb
# == Schema Information
#
# Table name: feedly_sources
#
#  id          :integer          not null, primary key
#  feed_id     :string
#  title       :string
#  description :string
#  icon_url    :string
#  enabled     :boolean          default(TRUE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class FeedlySource < ActiveRecord::Base
  validates :feed_id, presence: true,
                      uniqueness: true

  has_many :feedly_articles, dependent: :destroy
  has_many :interest_sources, dependent: :destroy
  has_many :interests, through: :interest_sources
end

app/controllers/admin/feedly_sources_controller.rb
class Admin::FeedlySourcesController < AdminController
  before_action :set_feedly_source, only: [:show, :update]
  before_action :enabled_state, only: :update

  def index
    @feedly_sources = FeedlySourcesFinder.collection(params: { page: page })
  end

  def show
  end

  def update
    @feedly_source.update(feedly_source_params)

    if !@feedly_source.enabled && @feedly_source.enabled != enabled_state
      @feedly_source.feedly_articles.destroy_all
    end

    redirect_to admin_feedly_sources_url
  end

  private

  def set_feedly_source
    @feedly_source = FeedlySource.find(params[:id])
  end

  def enabled_state
    @enabled_state ||= @feedly_source.enabled
  end

  def feedly_source_params
    params.require(:feedly_source).permit(:interest_id, :enabled)
  end
end

app/helpers/admin/feedly_sources_helper.rb
module Admin::FeedlySourcesHelper
end

app/views/admin/feedly_sources/index.html.slim
= render 'admin/partials/sidebar'

div id="main"
  .title-panel
    h3
      |Feedly sources
  .data-wrapper         
    table class="table table-bordered"
      thead
        tr
          th
            |Icon
          th
            |Title
          th
            |Group
          th
            |Articles amount

      tbody
        - @feedly_sources.each do |feedly_source|
          tr
            td
              img src="#{feedly_source.icon_url}"
            td
              = link_to feedly_source.title, admin_feedly_source_path(feedly_source)
            td
              - feedly_source.interests.each do |interest|
                = interest.name
                br
            td
              = feedly_source.feedly_articles.count

  .pagination-container
    = paginate @feedly_sources

app/views/admin/feedly_sources/show.html.slim
= render 'admin/partials/sidebar'

div id="main"
  .title-panel
    h3
      = @feedly_source.title
  .feedly-source-container
    h4
      |Description
    p
      = @feedly_source.description
    h4
      |Last article date
    p
      - if @feedly_source.feedly_articles.any?
        = @feedly_source.feedly_articles.last.publish_date
      - else
        | -

    = form_for @feedly_source, url: admin_feedly_source_path(@feedly_source) do |f|
      .form-group
        = f.label :enabled
        = f.check_box :enabled
      = f.submit 'Save', class: 'btn btn-default'